# Generated by Django 3.0.5 on 2020-09-17 15:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, unique=True, verbose_name='email address')),
                ('username', models.CharField(default='', max_length=15, unique=True)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_dietitian', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=300)),
                ('price', models.FloatField(default='')),
                ('is_plusplan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('created_by', models.CharField(default='', max_length=100)),
                ('created_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dietitian',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(default='', max_length=10)),
                ('middlename', models.CharField(default='', max_length=10)),
                ('lastname', models.CharField(default='', max_length=10)),
                ('mobile_no', models.CharField(default='', max_length=10)),
                ('qualification', models.CharField(default='', max_length=10)),
                ('image', models.ImageField(upload_to='diet_app')),
                ('commission_smartplan', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('commission_smartplan_healthIssue', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('commission_smart_plusplan', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('commission_smart_plusplan_healthIssue', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(default='', max_length=500)),
                ('sender', models.CharField(default='', max_length=100)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.Room')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(default='', max_length=10)),
                ('middlename', models.CharField(default='', max_length=10)),
                ('lastname', models.CharField(default='', max_length=10)),
                ('age', models.IntegerField(blank=True, default=10, null=True)),
                ('gender', models.CharField(default='', max_length=11)),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mobile_no', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=500)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updates_at', models.DateField(null=True)),
                ('date_tofill_form', models.DateField(blank=True, null=True)),
                ('new_weight', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('plan_end_date', models.DateField(blank=True, null=True)),
                ('chat_count', models.IntegerField(blank=True, default=0, null=True)),
                ('is_data_filled', models.BooleanField(default=False)),
                ('is_chart_sent', models.BooleanField(default=False)),
                ('payment_uuid', models.CharField(default=uuid.uuid1, max_length=200)),
                ('d_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet_app.dietitian')),
                ('p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet_app.Plans')),
            ],
        ),
        migrations.CreateModel(
            name='Room_Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_member', models.BooleanField(default=False)),
                ('added_by', models.CharField(default='', max_length=40)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.Room')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.UserData')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.Plans')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.UserData')),
            ],
        ),
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=datetime.datetime(2020, 9, 17, 20, 42, 49, 149743))),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('type', models.CharField(default='', max_length=70)),
                ('room_id', models.IntegerField(blank=True, null=True)),
                ('dietitan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.dietitian')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.UserData')),
            ],
        ),
    ]
