# Generated by Django 3.0.5 on 2020-10-03 15:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('review', models.CharField(default='', max_length=300)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2020, 10, 3, 20, 56, 47, 641638))),
                ('image', models.ImageField(default='/diet_app/avatar.png/', upload_to='diet_app')),
            ],
        ),
        migrations.CreateModel(
            name='poster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='diet_app')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserHealthData',
            fields=[
                ('userdata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='diet_app.UserData')),
                ('workout', models.BooleanField(default=False)),
                ('workout_time', models.CharField(default='', max_length=15)),
                ('workout_time_inday', models.CharField(default='', max_length=20)),
                ('workout_day_inweek', models.CharField(default='', max_length=20)),
                ('want_to_achive', models.CharField(default='', max_length=30)),
                ('type', models.CharField(default='', max_length=30)),
                ('dishes', models.CharField(default='', max_length=30)),
                ('have_disease', models.BooleanField(default=False)),
                ('supplements', models.CharField(default='', max_length=200)),
                ('about', models.CharField(default='', max_length=300)),
            ],
            options={
                'verbose_name_plural': "Cutomer's Health Data",
            },
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name_plural': 'Authentication'},
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name_plural': 'Cutomers'},
        ),
        migrations.RenameField(
            model_name='dietitian',
            old_name='commission_smart_plusplan_healthIssue',
            new_name='commission_smartplusplan',
        ),
        migrations.RenameField(
            model_name='dietitian',
            old_name='commission_smart_plusplan',
            new_name='commission_smartplusplan_healthissue',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='dietitan',
            new_name='dietitian',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='chat_count',
            new_name='call_count',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='address',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='d_id',
            new_name='dietitian',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='p_id',
            new_name='plan',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='new_weight',
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 3, 20, 56, 47, 636635)),
        ),
        migrations.AddField(
            model_name='myuser',
            name='ref_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='plans',
            name='is_healthissue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diet_app.meeting'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_feed_remain',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='plan_buy_count',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='userdata',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userdata',
            name='referral_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 3, 20, 56, 47, 636635)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diet_app.Plans'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='payment_uuid',
            field=models.CharField(blank=True, default=uuid.uuid1, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Workout_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.UserHealthData')),
            ],
        ),
        migrations.CreateModel(
            name='Week_Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('old_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('new_weight', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('query', models.CharField(default='', max_length=400)),
                ('date', models.DateField(default=datetime.datetime(2020, 10, 3, 20, 56, 47, 632633))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.UserData')),
            ],
        ),
    ]
