# Generated by Django 3.0.5 on 2020-10-04 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0002_auto_20201003_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietitian',
            old_name='commission_smartplan_healthIssue',
            new_name='commission_smartplan_healthissue',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 9, 39, 30, 518559)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 4, 9, 39, 30, 513555)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 4, 9, 39, 30, 513555)),
        ),
        migrations.AlterField(
            model_name='week_report',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
